# use conda env create -f conda_environment.yml
name: romer
channels:
  - defaults
dependencies:
  - python=3.6
  - h5py
  - jupyter
  - matplotlib
  - numpy
  - pillow
  - scikit-image
  - scipy
  - pip:
    - tensorflow-gpu
    - keras
